# Main Listener Port
listeners.tcp.default = 5672

# User Credentials & Default VHost
default_user = devuser
default_pass = devpassword
default_vhost = /

# Boot-Time Schema/Topology Import
definitions.import_backend = local_filesystem
definitions.local.path = /etc/rabbitmq/definitions.json
